### ISSUE TITLE
Bug: lm_optimize throws error

### ISSUE THREAD

**Issue by hammondm** [coqui-ai/STT#2202]
Hi

I've tried it a couple of different ways and `lm_optimize()` always comes back that `lm_opt` is not defined, as below.

I tried `python -m coqui_stt_training.util.lm_optimize` as well with the same error.

mike h

```
python lm_optimizer.py --test_files /mhdata/cvnew/clips/tst.csv --checkpoint_dir fordata/mhwelsh/welsh/checkpoints --n_hidden 200 --scorer_path fordata/newwelsh.scorer
Using the top level lm_optimizer.py script is deprecated and will be removed in a future release. Instead use: python -m coqui_stt_training.util.lm_optimize
2022-04-24 22:22:02.584403: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
2022-04-24 22:22:04.263143: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2299965000 Hz
2022-04-24 22:22:04.265496: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x53a4130 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-04-24 22:22:04.265560: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2022-04-24 22:22:04.271188: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2022-04-24 22:22:05.976601: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-24 22:22:05.976833: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x58bdfd0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2022-04-24 22:22:05.976853: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce RTX 2080 Super with Max-Q Design, Compute Capability 7.5
2022-04-24 22:22:05.977046: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-24 22:22:05.977177: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1666] Found device 0 with properties:
name: NVIDIA GeForce RTX 2080 Super with Max-Q Design major: 7 minor: 5 memoryClockRate(GHz): 1.08
pciBusID: 0000:01:00.0
2022-04-24 22:22:05.977214: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2022-04-24 22:22:05.988396: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2022-04-24 22:22:06.017602: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2022-04-24 22:22:06.018920: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2022-04-24 22:22:06.022358: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.11
2022-04-24 22:22:06.035457: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2022-04-24 22:22:06.035625: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2022-04-24 22:22:06.035725: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-24 22:22:06.035919: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-24 22:22:06.036020: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1794] Adding visible gpu devices: 0
2022-04-24 22:22:06.036259: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2022-04-24 22:22:07.039992: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1206] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-04-24 22:22:07.040027: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212]      0
2022-04-24 22:22:07.040034: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1225] 0:   N
2022-04-24 22:22:07.040481: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-24 22:22:07.040668: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1082] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-24 22:22:07.040809: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1351] Created TensorFlow device (/device:GPU:0 with 6660 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Super with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 7.5)
I --alphabet_config_path not specified, but found an alphabet file alongside specified checkpoint (fordata/mhwelsh/welsh/checkpoints/alphabet.txt). Will use this alphabet file for this run.
Traceback (most recent call last):
  File "lm_optimizer.py", line 16, in <module>
    lm_optimize.main()
  File "/code/training/coqui_stt_training/util/lm_optimize.py", line 86, in main
    results = lm_opt.compute_lm_optimization()
NameError: name 'lm_opt' is not defined
```

**Comment by wasertech** [comment]
I'm gessing you are using version 1.2.0.
You can either upgrade to v1.3.0 or fix the import path manually.
Replace
```
from coqui_stt_training.util.lm import optimize as lm_opt
```
With
```
from coqui_stt_training.util import lm_optimize as lm_opt
```
inside `lm_optimize.py`.
See #2116 and #2148 for more context.

**Comment by JRMeyer** [comment]
can you verify what version of `STT` you're using? 

you're using which image from Docker?

It might be the case this was fixed in `v1.3.0`

**Comment by hammondm** [comment]
Thanks guys:

I pulled the "latest" image a few days ago and it says 1.4.0.

Adding the line above to the file in `/code` didn't work, but adding it to the file in `/code/training/util` did.

Thanks!
mike h

**Comment by hammondm** [comment]
o.k., a couple of other things:

1. One has to specify `--n_trials 6` explicitly.
2. the `lm_optimizer.py` program requires you already have a scorer and that means you already have to set alpha and beta, right?
3. So what do we do with the alpha and beta produced by `lm_optimizer.py`? My best guess at this point is that we recreate the scorer?

mike h.

**Comment by wasertech** [comment]
> Adding the line above to the file in `/code` didn't work, but adding it to the file in `/code/training/util` did.

Ha yes if you are using the current alpha build of STT v1.4.0 the `lm_opt` has been left out by mistake, you can just delete the reference of `lm_opt` in the module.

I've PR the changes to main, thanks for spotting it.

See #2203

**Comment by FrontierDK** [comment]
I just did a fresh install in an Kubuntu VM, and the error is still there.

```
python -m coqui_stt_training.util.lm_optimize --alphabet_config_path ~/Python-3.7.6/STT/data/alphabet.txt --scorer_path ~/kenlm.scorer --auto_input_dataset ~/speech/sample.csv --checkpoint_dir ~/coqui-stt-1.3.0-checkpoint --n_trials 6 --n_hidden 2048 --lm_alpha_max 1 --lm_beta_max 2

I Processing --auto_input_dataset input: /home/me/speech/sample.csv...
I Using specified --alphabet_config_path: /home/me/Python-3.7.6/STT/data/alphabet.txt
I Generated train set size: 6 samples.
I Generated validation set size: 3 samples.
I Generated test set size: 3 samples.
I Writing train set to /home/me/speech/train.csv
I Writing dev set to /home/me/speech/dev.csv
I Writing test set to /home/me/speech/test.csv
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/me/Python-3.7.6/STT/training/coqui_stt_training/util/lm_optimize.py", line 97, in <module>
    main()
  File "/home/me/Python-3.7.6/STT/training/coqui_stt_training/util/lm_optimize.py", line 86, in main
    results = lm_opt.compute_lm_optimization()
NameError: name 'lm_opt' is not defined
(coqui-stt-train-venv) me@kubuntu1uefi:~/Python-3.7.6/STT$
```

**Comment by wasertech** [comment]
@FrontierDK wait for my branch to merge with main :)

**Comment by FrontierDK** [comment]
> @FrontierDK wait for my branch to merge with main :)

I'll go to bed now (close to midnight here) and try a new fresh install tomorrow. Thank you for fixing :)

**Comment by HarikalarKutusu** [comment]
> So what do we do with the alpha and beta produced by lm_optimizer.py? My best guess at this point is that we recreate the scorer?

@hammondm , not exactly. That was also my first impression thou...

0. You have the acoustic model and scorer.
1. You might like to run a test (.evaluate) with this non-optimized scorer (default alpha/beta)
2. You run lm_optimize to find better values for alpha & beta, it is a random walk, the more steps, the better. It is a costly process. This will result in best alpha/beta values.
3. You may run the test again with these new parameters to see if they are better.
4. You use these values in the inference engine. The tflite acoustic model and your scorer will be the same. Use lm_alpha, lm_beta parameters...

**Comment by FrontierDK** [comment]
I just tried again in a newly installed VM, and it still fails.

I did a _git clone https://github.com/coqui-ai/STT_ - so it should be fresh?

**Comment by wasertech** [comment]
@FrontierDK the fix is on my branch [wasertech/STT#fix-compute_lm_opt](https://github.com/wasertech/STT/tree/fix-compute_lm_opt) it’s not merged with main yet checkout the status of the fix here: #2203

**Comment by wasertech** [comment]
@FrontierDK you can now retry as it has been merged now.

**Comment by FrontierDK** [comment]
I can confirm that the bug is now gone :)

**Comment by sjpritchard** [comment]
This still occurs in the 1.4.0a1 docker image

**Comment by wasertech** [comment]
> This still occurs in the 1.4.0a1 docker image

@sjpritchard Try with `main` instead of `latest`.

```
$ docker pull ghcr.io/coqui-ai/stt-train:main
$ docker run -it ghcr.io/coqui-ai/stt-train:main
```
